apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  releaseName: sealed-secrets-controller
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: sealed-secrets
    version: 1.4.0
  values:
    crd:
      keep: false
