kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sealed-secrets-management
rules:
  - apiGroups: ["bitnami.com"]
    resources: ["sealedsecrets"]
    verbs: ["get", "patch", "delete", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sealed-secrets-crb
roleRef:
  apiGroup: bitnami.com
  kind: ClusterRole
  name: sealed-secrets-management
subjects:
  - kind: ServiceAccount
    name: sealed-secrets-controller
    namespace: kube-system
